spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=${URL_BASE}
spring.jpa.hibernate.ddl-auto=${STATUS_SQL}
spring.jpa.show-sql=${STATUS_BASE}
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${EXPIRATION_TIMER}
google.places.api.key=${GOOGLE_PLACES_API_KEY}
google.places.api.url=${GOOGLE_PLACES_API_URL}